apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "harbor.core" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
data:
  app.conf: |+
    appname = Harbor
    runmode = prod
    enablegzip = true

    [prod]
    httpport = 8080
  LOG_LEVEL: "{{ .Values.logLevel }}"
  CONFIG_PATH: "/etc/core/app.conf"
  CHART_CACHE_DRIVER: "redis"
  _REDIS_URL: "{{ template "harbor.redisForCore" . }}"
  _REDIS_URL_REG: "{{ template "harbor.redisForGC" . }}"
  PORTAL_URL: "http://{{ template "harbor.portal" . }}"
  REGISTRYCTL_URL: "http://{{ template "harbor.registry" . }}:8080"
  CLAIR_HEALTH_CHECK_SERVER_URL: "http://{{ template "harbor.clair" . }}:6061"
  ADMINSERVER_URL: "http://{{ template "harbor.adminserver" . }}"
